name: Nightly build MacOS (without freetype)

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: | 
        curl http://www.libsdl.org/release/SDL2-2.0.10.dmg > SDL2-2.0.10.dmg
        hdiutil attach SDL2-2.0.10.dmg >>/dev/stderr
        cp -R -v /Volumes/SDL2/SDL2.framework $HOME/Library/Frameworks
        echo "ls Frameworks"  >>/dev/stderr
        ls $HOME/Library/Frameworks/ >>/dev/stderr
        hdiutil eject /Volumes/SDL2 >>/dev/stderr 
        brew install autoconf automake

    - name: setup
      run: |
        autoreconf -ivf
        ./configure  
        echo "CFLAGS = -DREVISION=$(svn info --show-item revision svn://servers.simutrans.org/simutrans) " >>config.default
        
        mv config.default cfd
        sed 's/BACKEND = posix/#BACKEND = posix/' cfd | sed 's/#BACKEND = sdl2/BACKEND = sdl2/' > config.default
        cat config.default >>/dev/stderr

    - name: make
      run: make -VERBOSE=1
      
    - name: distribute
      run: sh ./distribute.sh

    - name: Rename result  
      run:  |
          ls *.zip >>/dev/stderr
          echo ::set-env name=LATEST::$(ls *.zip)
          mv sim*.zip simumac-nightly.zip

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./simumac-nightly.zip
        asset_name: simumac-nightly.zip
        tag: Nightly
        overwrite: true   
